# Generated by Django 4.0 on 2022-04-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='photo',
        ),
    ]
