# Generated by Django 4.0 on 2022-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_image_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='post_pic'),
        ),
    ]
